# Generated by Django 5.2.7 on 2026-03-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_dashboard_data_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundOrderRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_nbr', models.CharField(db_index=True, max_length=255)),
                ('facility', models.CharField(db_index=True, max_length=255)),
                ('remark', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outbound Order Remark',
                'verbose_name_plural': 'Outbound Order Remarks',
                'unique_together': {('order_nbr', 'facility')},
            },
        ),
    ]
