# Generated by Django 5.2.7 on 2026-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_add_status_override_to_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], db_index=True, max_length=20)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February')], db_index=True, max_length=20)),
                ('kpi', models.CharField(choices=[('Delivery Fulfilment', 'Delivery Fulfilment'), ('On Time Delivery', 'On Time Delivery'), ('PODs submission', 'PODs submission')], db_index=True, max_length=50)),
                ('region', models.CharField(choices=[('Fuchs-Yanbu', 'Fuchs-Yanbu'), ('Fuchs-Jeddah', 'Fuchs-Jeddah')], db_index=True, max_length=30)),
                ('total', models.CharField(blank=True, default='', max_length=30)),
                ('hit', models.CharField(blank=True, default='', max_length=30)),
                ('miss', models.CharField(blank=True, default='', max_length=30)),
                ('achieved_percent', models.CharField(blank=True, default='', help_text='مثال: 90 أو 100 (نسبة ACHIEVED)', max_length=20)),
                ('target_percent', models.CharField(blank=True, default='98', help_text='مثال: 98', max_length=20)),
            ],
            options={
                'verbose_name': 'Transportation KPI',
                'verbose_name_plural': 'Transportation KPIs',
                'ordering': ['section', 'month', 'kpi', 'region'],
                'unique_together': {('section', 'month', 'kpi', 'region')},
            },
        ),
    ]
