# Generated by Django 5.2.7 on 2026-03-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_transportation_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationkpi',
            name='sum_value',
            field=models.CharField(blank=True, default='', help_text='SUM (يُعرض لـ On Time Delivery فقط)', max_length=30),
        ),
    ]
