# Generated by Django 5.2.7 on 2026-03-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_transportation_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationkpi',
            name='total_submitted',
            field=models.CharField(blank=True, default='', help_text='TOTAL SUBMITTED (يُستخدم مع KPI = PODs submission)', max_length=30),
        ),
    ]
