# Generated by Cursor on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_transportation_kpi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingpoint",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]

